language: python

sudo: required
dist: trusty

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.2
      - python-dev
      - libgdal1-dev
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran

services:
  - postgresql

python:
  - "2.7"
  - "

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - sudo apt-get -qq update

install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install git+https://github.com/OpenDataAnalytics/gaia.git@basegaia#egg=gaia
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_ci_test

script:
  - python -m unittest discover
  - flake8 --config tests/flake8.cfg gaia_twitter tests
